/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cunist_CalculateByGPU */

#ifndef _Included_cunist_CalculateByGPU
#define _Included_cunist_CalculateByGPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cunist_CalculateByGPU
 * Method:    inference
 * Signature: ([B[D)I
 */
JNIEXPORT jint JNICALL Java_cunist_CalculateByGPU_inference
  (JNIEnv *, jobject, jbyteArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
